### ISSUE TITLE
accessing full text via the API

### ISSUE THREAD

**Issue by howardjong** [cambialens/lens-api-doc#11]
How do I get access to the indexed full_text data?
 
I’ve not been able to call it, or view the article full text after filtering by has_fulltext.
 
I’m trying to access using Python. Please advise. Thanks!

**Comment by denizk** [comment]
Hi @howardjong 

We currently do not provide the full text as a retrievable field in the response.
However, you can perform searches on the indexed [full_text](https://docs.api.lens.org/request.html#full_text) field to find records of interest.

**Comment by howardjong** [comment]
If the full-text feature does become available, could you please let me know?

**Comment by denizk** [comment]
yes sure. If you haven't done so yet, feel free to fill out our API survey at https://lensorg.typeform.com/to/QM6aMm so we can better understand your needs.

**Comment by hugochan** [comment]
Hi @denizk , would like to follow up on this feature request. Is full text access fully supported now via the API?

I notice there is a [description field](https://docs.api.lens.org/response-patent.html#response-fields) in the patent response which contains the description text of a patent document. Together with claims and other meta data retrieved via API, we can almost "reconstruct" the full text shown on the [patent website page](https://www.lens.org/lens/patent/156-096-222-444-878/fulltext?l=en), but there is still some info not covered via API such as "29 Claims, 2 Drawing Sheets, and 2 Figures”.

**Comment by AaronBallagh** [comment]
Hello @hugochan,
Thank you for this question. Full text search is supported where full text is available, but the text has been normalised and parsed into individual fields. This is why the description field does not contain line break characters or other formatting and figures are not indexed.

**Comment by hugochan** [comment]
> Hello @hugochan,
> Thank you for this question. Full text search is supported where full text is available, but the text has been normalised and parsed into individual fields. This is why the description field does not contain line break characters or other formatting and figures are not indexed.

@AaronBallagh thanks for the prompt reply! Do we provide a way to directly fetch the full text via the API? Currently, I have to combine all the individual fields fetched via the API to approximately "reconstruct" the full text. However, the reconstructed text is a subset of the real full text. I noticed that some info such as the "29 Claims, 2 Drawing Sheets, and 2 Figures” statement is missing in all the fields I can fetch via the API.

**Comment by AaronBallagh** [comment]
Hi @hugochan, there is no way to fetch the entire full text via the API. Reconstructing the full text from individual fields as you have done is the best approach currently, noting that not all text has been parsed into individual fields.
