### ISSUE TITLE
Request limit status

### ISSUE THREAD

**Issue by dtmac** [cambialens/lens-api-doc#13]
Hi, how can I know the number of remaining records that I can fetch in a month, and the corresponding reset date? I am using python. Many thanks in advance

**Comment by rosharma** [comment]
Hi @dtmac , you can find `x-rate-limit-remaining-request-per-month` and `x-rate-limit-remaining-record-per-month` in your response headers. Similarly, you can find the reset date from `x-rate-limit-reset-date` in your response header. Fore more details please visit the [rate limiting](https://docs.api.lens.org/getting-started.html#rate-limiting) section in our API Documentation.

**Comment by dtmac** [comment]
Many thanks @rosharma9.

I understand that my corresponding reset date is 2019-10-12T00:27:49.018Z.
Could you help me understand what would be the "remaining request per month" here?

In: response.headers
Out: {'Date': 'Tue, 17 Sep 2019 09:56:32 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'x-rate-limit-reset-date': '2019-10-12T00:27:49.018Z', 'x-rate-limit-remaining-request-per-minute': '9', 'x-rate-limit-retry-after-seconds': '2125876', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding'}

**Comment by rosharma9** [comment]
Hi @dtmac ,
Looks like you are already rate limited. You should get the reason message in your response body (either its request or record based limit). As you are rate limited, you will only be able to perform successful request after `x-rate-limit-retry-after-seconds`.

**Comment by dtmac** [comment]
Clear. Thanks for your support @rosharma9
