### ISSUE TITLE
[Question] How to search for multiple authors in one query?

### ISSUE THREAD

**Issue by Mitchell-Faas** [cambialens/lens-api-doc#14]
Hi,

I'm currently developing an application which has to be able to do a search akin to the following: (firstname = Peter AND lastname = Jones) OR (firstname = Frank AND lastname = Mitchell)
Currently however, I have not been able to figure out how to do this and I would like some help.

I know that if I were to used the idea of `{"match": {"author.first_name": "Peter Frank"}}`, then both would be returned, but also anyone named Peter Mitchell or Frank Jones would be returned.

My base query is this:
```
{
  "query": {
    "bool": {
         "must": [
           {"match": {"author.first_name": "Peter"}}, 
           {"match": {"author.last_name": "Jones"}}
         ]
    }
  },
  "size": 5
}
```

**Comment by rosharma9** [comment]
Hi @Mitchell-Faas ,
You can use the [display_name](https://docs.api.lens.org/request.html#author-display_name) field to match the exact full name of an author.

```
"query": {
    "bool": {
      "should": [
        {"match_phrase": { "author.display_name": "Peter Jones" }},
        {"match_phrase": { "author.display_name": "Frank Mitchell" }}
      ]
    }
  }
```
Cheers
