### ISSUE TITLE
API 404 error

### ISSUE THREAD

**Issue by sfitzm** [cambialens/lens-api-doc#15]
I’m getting a 404 error with this query but I’m not sure why – I believe it may be that none of these DOI's are available within Lens, but I would have thought this would return 0 results rather than a 404 error.

 
{
  "query": {
    "terms": {
      "doi": ["10.1111/ajps.12471", "10.1111/ajps.12474", "10.1111/ajps.12473", "10.1111/ajps.12475", "10.1111/ajps.12467", "10.1111/ajes.12293", "10.1111/ajes.12292", "10.1111/ajes.12294", "10.1111/ajes.12295", "10.1111/ajes.12290", "10.1111/ajes.12297", "10.1111/ajes.12296", "10.1111/ajes.12291", "10.1080/08913811.2019.1647679", "10.1080/08913811.2019.1649880"]
    }
  },
  "size": 1000,
  "from": 0,
  "include": [
    "title",
    "lens_id",
    "external_ids",
    "abstract"
  ],
  "sort": [
    {
      "created": "desc"
    },
    {
      "year_published": "asc"
    }
  ],
  "exclude": null,
  "scroll": null,
  "scroll_id": null
}

**Comment by rosharma9** [comment]
Hi @sfitzm , Those DOIs looks to be the recent addition and haven't indexed yet in Lens. They will be available later this week after data update release.
Regarding 404, we will fix it in our next API update too.
Thank you.

**Comment by rosharma9** [comment]
This has been fixed now.
