### ISSUE TITLE
Getting persistent author_ids from query result

### ISSUE THREAD

**Issue by tsaltena** [cambialens/lens-api-doc#16]
Hi all,

I'm attempting to use the scholarly API to group scholarly outputs for certain authors for certain geography's. For the implementation, it would be ideal to be able group the outputs based on persistent unique identifiers. I noticed that there's a toggle for mag/pubmed PIDs in the web-interface ('Author Identifiers Enabled'). However, these identifiers don't seem to be available in the the API. Is this deliberate, or is it on the roadmap for future releases?

**Comment by rosharma9** [comment]
Hi @tsaltena, Thank you for your feedback. Yes, it is on the roadmap and will be part of our future releases. I have marked it as `feature request`.

**Comment by rosharma9** [comment]
Hi @tsaltena Author identifiers are available in the API now.
https://docs.api.lens.org/response.html#author
