### ISSUE TITLE
API seems to require credentials for preflight OPTIONS request

### ISSUE THREAD

**Issue by tomzeppenfeldt** [cambialens/lens-api-doc#17]
When sending an API request, we get a 401 for the OPTIONS request

Has your server been designed with OPTIONS in mind?  In that case, it should exclude user credentials .. see : https://www.w3.org/TR/cors/#cross-origin-request-with-preflight-0.

**Comment by rosharma9** [comment]
@tomzeppenfeldt For current version of the API, you might need to setup a proxy layer if you are intending to integrate with your frontend app.
For integrating the API, you should contact `support@lens.org` to discuss options. Cheers
