### ISSUE TITLE
how to query data with the patent publication key  as a condition

### ISSUE THREAD

**Issue by yamin369** [cambialens/lens-api-doc#2]
Whether the API  service  provides an  interface for querying data by **patent publication key**  of the patent ( for example 'US10172347B2' ),
If it doesn't provide , is there an interface method for querying the corresponding **lens_id** by publication key?  Beacause  I can only  query data by lens_id now .
Thank you for your help and consideration.

**Comment by rosharma9** [comment]
Hi @yamin369 , We currently do not have a lens_id resolver service endpoint through API. To retrieve the corresponding lens_id, `patent collection export` (https://www.lens.org/lens/user/collections) is probably easiest way to do this in bulk, or you can retrieve the lens_id for smaller datasets through the UI (https://www.lens.org/lens/search?q=US10172347B2)
We are currently working on patent API, it certainly will be easier when it's online.

**Comment by fros1y** [comment]
Now that the patent API is available, can this be revisited? Is there an endpoint for the patent API that will allow patents to be fetched by EPODOC?

**Comment by rosharma9** [comment]
Yes, there are few alternatives. This might work for you by using Jurisdiction with list of document numbers
```
{
    "query": {
        "bool": {
            "must":[
                    {
                        "match": {"jurisdiction": "US"}
                    },{"terms": {
                        "doc_number": ["6419946", "6998426"]
                    }
                }
            ]
        }
    },
    "include": ["lens_id", "biblio.invention_title"]
}
```
