### ISSUE TITLE
Filtering by creation date

### ISSUE THREAD

**Issue by magd-kudama-dev** [cambialens/lens-api-doc#25]
I wanted to know whether it's possible to filter by `created` or `published_date` (in a range)? If yes, how?

Do I have access to all ElasticSearch capabilities (I'm assuming you're using ES given the formatting of the API).

Thank you.

**Comment by rosharma9** [comment]
You can use like this:
https://docs.api.lens.org/examples.html#get-30-works-from-an-institution-published-between-two-years
```
"filter": {
	"range": {
		"created": {
			"gte": "2018-05-12",
			"lte": "2020-05-12"
		}
	}
}
```

Yes, you have access to queries but we haven't enabled aggregations.

**Comment by magd-kudama-dev** [comment]
Thanks, yea I figured but never closed the issue, sorry.
