### ISSUE TITLE
How to extract mutiple article knoing author and title 

### ISSUE THREAD

**Issue by JeremyDOPABAT** [cambialens/lens-api-doc#26]
Good morning !

I would like to know if it's possible to have multiple titles lignes and authors lines in this kind of request : 

{
	"query": {
		"match_phrase": {
			"title": "Based on the User-Centered Design and Development of Fiber Sensor Monitoring System"
		}
	},
	
	"sort": [{
		"year_published": "desc"
	}]
}'

y also try the querry fil with bool but nothing seems to work.

if we suppose we have to title T1 and T2 and two author A1 ad A2.
i would like to do TI and AI or T2 and A2

**Comment by rosharma9** [comment]
Hi,
This should work for you.

```
{
    "query": {
        "bool": {
            "should": [
                { 
                    "bool": {
                        "must": [
                            {"match": {"tite": "T1"}},
                            {"match": {"author.display_name": "A1"}}
                        ]
                    }
                },
                { 
                    "bool": {
                        "must": [
                            {"match": {"tite": "T1"}},
                            {"match": {"author.display_name": "A1"}}
                        ]
                    }
                }
            ]
        }
    },
    "include":["lens_id","authors"]
}
```

https://docs.api.lens.org/request.html#boolean-query
You can use `must` for AND operation and `should` for OR.

You can use `match_phrase` instead of `match` for exact comparison.

Please let me know if that doesn't work for you.
Cheers

**Comment by JeremyDOPABAT** [comment]
thanks for your help, 
i tried what you said but sadly that doesnt work for me.

here is the exemple 
`request <- '{

    "query": {
        "bool": {
            "should": [
                { 
                    "bool": {
                        "must": [
                            {"match_phrase": {"tite": "Role of interface dipole in metal gate/high-k effective work function modulation by aluminum incorporation"}},
                            {"match_phrase": {"author.display_name": "Zhenya Yang"}}
                        ]
                    }
                },
                { 
                    "bool": {
                        "must": [
                            {"match_phrase": {"tite": "Based on the User-Centered Design and Development of Fiber Sensor Monitoring System"}},
                            {"match_phrase": {"author.display_name": "Juan Ni Li"}}
                        ]
                    }
                }
            ]
        }
    },
    "include":["lens_id","authors"]
}'
`

as you said i use match phrase instead of match

i pick up two exemple on lens.org so I should get result. 
Any idea to explain my error ?

**Comment by rosharma9** [comment]
Hi @JeremyDOPABAT ,
Your query is correct, however there is a typo in the field name `tite` (it should be `title`).
Cheers

**Comment by JeremyDOPABAT** [comment]
oh thanks how could i've not see that !!!!!

**Comment by JeremyDOPABAT** [comment]
that is working
