### ISSUE TITLE
How to get cinting works 

### ISSUE THREAD

**Issue by JeremyDOPABAT** [cambialens/lens-api-doc#27]
Dear every body, 
I would like to know what's publication is citing a knowing publication. 

for exemple : 
https://www.lens.org/lens/scholar/article/146-875-730-051-907/citations/citing
i would like to know at least the ids of the 49 citing works.

do someone know how to do that with the api, please? 

thank you for your time. 
regards

**Comment by rosharma9** [comment]
Hi, you can use the following:

```
{
    "query": {
        "match": {
            "lens_id":"146-875-730-051-907"
        }
    },
    "include": ["scholarly_citations"]
}
```
For field descriptions please visit https://docs.api.lens.org/response.html#scholarly_citations
