### ISSUE TITLE
Searching by simple patent family members returns the list of extended family members

### ISSUE THREAD

**Issue by AaronBallagh** [cambialens/lens-api-doc#28]
In some cases, searching for a `lens_id` in the simple patent family field `family.simple.member.lens_id` returns the list of extended patent family members rather than the simple patent family members. e.g.
```
{
    "query": {
        "match": {
            "family.simple.member.lens_id": "179-225-554-278-418"
        }
    },
    "include": ["lens_id", "families.simple_family.members", "families.extended_family.members"]
}
```
In this example, the patent record `179-225-554-278-418` has **4** simple family members and **28** extended family members, however searching by the `family.simple.member.lens_id` returns the list of **28** extended family members.

This appears to be an issue with the simple family members in the search index only, family member data in records returned in the response are correct.

**Comment by denizk** [comment]
This was fixed in a recent index update.
