### ISSUE TITLE
Is scroll enabled on the patent API?

### ISSUE THREAD

**Issue by poldham** [cambialens/lens-api-doc#31]
Dear all, 

I am writing R code to access the scholarly API and Patent API (with subscription). The scroll is working fine with scholarly. However, for the patent API it doesn't.  The response to a call to the patent API includes the scrollid but when that is passed as the next request a 500 error is generated. Can you advise if scroll is enabled for the patent API or if something else is going on server side? I've tried this over the last few weeks and it keeps returning a 500, hence the question. 

Many thanks for the help on this!

Best, 

Paul

**Comment by rosharma9** [comment]
Hi @poldham, The scroll is working for Patent API as well. Can you please provide me an example of how you are implement it. It will help us debug the issue. Thank you

**Comment by poldham** [comment]
Hi, thanks very much. That was the information I needed to track the problem down. Confirming that the Patent API scroll is working.  It was a hard to spot bug in my code that I’ve now fixed! 

Thanks again, 

Best, 

Paul
