### ISSUE TITLE
List of aviable funding countries/countries general? [Scholar Api]

### ISSUE THREAD

**Issue by chmras** [cambialens/lens-api-doc#32]
When i want to search for a funding country, the documentation at https://support.lens.org/scholar-field-definitions/, says following:

label | group | example | definition
Funding Country | Funding | "United Kingdom" | The country of the funding body

However, if i search for a small country, Eg 'Luxembourg', it gets me a hit reply, even with a relatively broad period of 15 months search period.
It could be that there simply is no funding information tagged on Luxembourg. Alternatively i'm writing it wrong.

So, is it possible to get a list of supported country names?
Also, your mainpage, the none api method supports using country codes such as UK, LU for search methods of countries.
Is this allowed as well on the api, or is this only a full country name search method?

**Comment by AaronBallagh** [comment]
Hi Martin,

Your request is correct, but there are currently no records with funding country from 'Luxembourg' in our data. We currently store the raw country value for funding records, which come from Crossref and PubMed. Most of these can be mapped to an ISO 3166-1 country code like other country fields and we'll be standardizing the funding country field to use ISO country codes in future as well. 

Attached is an extract of the current funding country values [funding_country.txt](https://github.com/cambialens/lens-api-doc/files/6153116/funding_country.txt)

Cheers,
Aaron

**Comment by chmras** [comment]
Hi Aaron
It is what it is, regard no funding.country information for Luxembourg.
But thanks for the included country list. It will make those queries easier to do, for future lookups, now that i know the ‘valid country’ values.

Kind regards
Martin Rasmussen
ChronosHub
