### ISSUE TITLE
Patent API: Mismatch between results from the API and the website

### ISSUE THREAD

**Issue by m0bi5** [cambialens/lens-api-doc#35]
I am currently using the Patent API to search for patents with `applicant.name = "Virginia Polytechnic Institute And State Univ"`. The equivalent search on the website returns 41 results ([Link to search](https://www.lens.org/lens/search/patent/list?p=0&n=10&f=false&e=false&l=en&authorField=author&dateFilterField=publishedDate&presentation=false&stemmed=true&useAuthorId=false&applicant.must=VIRGINIA%20POLYTECHNIC%20INSTITUTE%20AND%20STATE%20UNIV&preview=true)), however, the API returns atleast 100 results. 

```
request = {
    #Terms to search for
    'query':{
        'match': {
            'applicant.name': 'Virginia Polytechnic Institute And State Univ'
        }
    },
    'size': 100
}
headers = {
    'Authorization': f'Bearer {key}', 
    'Content-Type': 'application/json'
}
response = requests.post(
    url='https://api.lens.org/patent/search',
    headers=headers,
    json=request
)
print(len(response.json()['result'])) #Prints 100, but 41 is expected
```

I have also tried `applicant.name.keyword='Virginia Polytechnic Institute And State Univ'` but that returns 0 results.

**Comment by rosharma9** [comment]
@m0bi5 you can use [match phrase](https://docs.api.lens.org/request-patent.html#match-phrase-query) query to search the exact phrase.
```
{
    "query": {
        "match_phrase": {
            "applicant.name": "Virginia Polytechnic Institute And State Univ"
        }
    }
}
```

**Comment by m0bi5** [comment]
@rosharma9 Thanks, that seems to be better. However, there is still a mismatch of around 5-10 records compared to that obtained from the website. Any idea why that may be the case?

**Comment by rosharma9** [comment]
@m0bi5 The link you shared is giving same results (46) as API.

But for some cases, there might be some difference in the results. Please refer to [this reply](https://github.com/cambialens/lens-api-doc/issues/33#issuecomment-800755292) for details.

**Comment by m0bi5** [comment]
Okay, thanks. The linked issue was helpful!
