### ISSUE TITLE
GET request issue: the body query doesn't work 

### ISSUE THREAD

**Issue by YasmeenAlsaedy** [cambialens/lens-api-doc#36]
Hello all, 
I tried to run a GET request using the Query DSL, but it is not working.
This is the cURL from postman:

```
curl --location --request GET 'https://pmr-beta.api.lens.org/patent/search' \
--header 'Authorization: Bearer my-access-token' \
--header 'Content-Type: application/json' \
--data-raw '{
        "query": {
            "terms":  {
                "lens_id": ["031-156-664-516-153"]
            }
}'
```

And it always gave me this error."
```
{
    "message": "Parameter 'query' cannot be empty.",
    "code": 400
}

```
"

Thank you for your help :)

**Comment by rosharma9** [comment]
@YasmeenAlsaedy You should use `POST` request to send the json body. 
For GET you need to provide the parameters in the query parameter.
This is an example for our scholarly api.
https://docs.api.lens.org/examples-scholar.html#using-get-requests

**Comment by YasmeenAlsaedy** [comment]
Oh! Thank you so much for your help ^^
