### ISSUE TITLE
source.issn is not working

### ISSUE THREAD

**Issue by ajay070993** [cambialens/lens-api-doc#42]
I was trying to filter journals based on source print issn number by using the following JSON but it is returning empty data.

{
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "title": {
                            "query": "ibrance",
                            "operator":"or"
                        }
                    }
                },
                {
                    "terms":{
                        "source.issn":[ "00155691"]
                    }
                }
            ]
        }
    }
}

**Comment by rosharma9** [comment]
It should be fixed now. Thanks
