### ISSUE TITLE
[Question] How do I search a list of paper by their titles in one query?

### ISSUE THREAD

**Issue by yd34-1560609** [cambialens/lens-api-doc#44]
I am trying to search 1000 papers at once and this query seems wrong. The 'count' is a list contains 1000 title's strings of paper. Will that work in any way?
`data = '''{
             "query": {
                        "terms": {
                                    "title": count
                                }
                    },
             "size": 1000,
             "sort": [
                   {
                        "year_published": "desc"
                   }
             ]
        }'''`

**Comment by yd34-1560609** [comment]
I actually found out it was my python and JSON issue. But still, is this method possible for getting 1000 papers at once?

**Comment by rosharma9** [comment]
You might need to use [match phrase](https://docs.api.lens.org/request-scholar.html#match-phrase-query) query like this:

```
{
    "query": {
        "bool": 
            {
                "should": [
                    {"match_phrase": {"title": "title string 1"}},
                    {"match_phrase": {"title": "title string 2"}},
                    ...
                ]
            }
    },
    "include":["lens_id", "external_ids", "source"]
}
```
