### ISSUE TITLE
Scholarly API endpoint, return more than 1000 results?

### ISSUE THREAD

**Issue by chmras** [cambialens/lens-api-doc#48]
I have a query, that gives me about 4800 results.
I page through each of those results by each 100th, however, when i reach number 1000 and forward, i get an error.

Query:
{"query":{"bool":{"must":[{"range":{"date_published":{"gte":"2021-01-01","lte":"2022-12-31"}}},{"bool":{"must":[{"match":{"external_id_type":"doi"}}]}},{"bool":{"should":[{"match_phrase":{"funding.organisation":"*some funding organisations*"}},...]}}]}},"size":10,"from":1000}

The reply back, i get, is:

{
    "reference": "bad_request",
    "message": "The result window is too large for allowed maximum of 1000.",
    "code": 400
}

**Comment by rosharma9** [comment]
We currently support two types of [pagination](https://docs.api.lens.org/request-scholar.html#pagination):
- [Offset/Size based](https://docs.api.lens.org/request-scholar.html#offsetsize-based-pagination): It is suitable to paginate through small dataset and limited to just 1000 records.
- [Cursor based](https://docs.api.lens.org/request-scholar.html#cursor-based-pagination): This is for downloading larger set of records.
In your case, you should use the second option. Here is an [python code example](https://docs.api.lens.org/samples-scholar.html#python---cursor-based-pagination) if you are integrating it programmatically.

**Comment by chmras** [comment]
@rosharma9  Thanks,
I had that in my implementation, but it didn't worked last time i tested it, but it seems to do now. 
I've created a new ticket with the new error ;)
