### ISSUE TITLE
How to [get] information instead of [post] 

### ISSUE THREAD

**Issue by ZiliGit** [cambialens/lens-api-doc#50]
Hi,

I am a newcomer to the Lens API. The example to use the patent API in the API documentation is to [post] instead of [get]. I wonder how can I modify the following codes in python to [get] the correct information. What I need to include in the header if I  do not use the "Bearer your-access-token" structure in the [post].

<img width="641" alt="API example" src="https://user-images.githubusercontent.com/67197221/161663915-85bef2ef-1e8e-420f-b352-2382883f0305.png">

Also, I would like to include the field like
 "include": ["reference_cited.patent.lens_id", "doc_key"], but when I tried this with the [post] request, it returns
<img width="833" alt="image" src="https://user-images.githubusercontent.com/67197221/161664236-f8d01c7e-d7ef-4bc3-b5a7-9acb39e5ded0.png"> 
But I am sure it is the correct field in the documentation.

Thanks for your help and time!

**Comment by rosharma9** [comment]
You can use `GET` requests with two endpoints listed [here](https://docs.api.lens.org/getting-started.html#api-resources):
1. Just single record by Lens ID
`https://api.lens.org/patent/031-156-664-516-153?token=YOUR_TOKEN&include=biblio.references_cited.citations.patcit,lens_id`

2. Search for multiple records
`https://api.lens.org/patent/search?token= YOUR_TOKEN&size=10&query=YOUR_QUERY&include=biblio.references_cited.citations.patcit,lens_id&sort=asc(date_published)`

We have two set of fields, one for [searching](https://docs.api.lens.org/request-patent.html#searchable-fields) and another for [response](https://docs.api.lens.org/response-patent.html#response-fields).  For `include` and `exclude` you will need to provide the response fields. 
Please let us know if you have further issues.

**Comment by ZiliGit** [comment]
Thanks for your prompt reply. I'll try that tomorrow and might have other problems.

Actually, I am confused about why the code example only provides [POST], which should be used only when someone wants to change the data, am I right? Also, I want to get patents' basic information as well as information on the cited patents under some broad class and need a relatively large number of patents. Is that possible for a free-trail account? 

Thanks a lot.

**Comment by rosharma9** [comment]
We have briefly mention it in API doc for [scholarly](https://docs.api.lens.org/examples-scholar.html#using-get-requests) and [patent](https://docs.api.lens.org/examples-patent.html#using-get-requests)
We will add a few code examples for GET. We considered POST for search to have preference over complex JSON based query. For large number of requests, please contact [subscriptions@lens.org](mailto:subscriptions@lens.org) with your use case.
Thank you

**Comment by ZiliGit** [comment]
Thanks for your clarification!

**Comment by rosharma9** [comment]
You can use our [Cursor Based pagination](https://docs.api.lens.org/request-patent.html#cursor-based-pagination). You can easily download 10K records with just 100 API calls with your temporary account (each request can access 100 records).  
[Here](https://docs.api.lens.org/samples-patent.html#cursor-based-pagination) is a python code example explaining how it works.
Thank you

**Comment by ZiliGit** [comment]
Hi,

Sorry, I have another question. Why when I use a string-based query, the response is code 400.
<img width="817" alt="image" src="https://user-images.githubusercontent.com/67197221/163687878-0229c43f-5142-430c-9910-98b3e465093e.png">

Thanks for your help!

**Comment by ZiliGit** [comment]
Hi,

Sorry I encountered another question when I try to use the string-based query to get the filtered patents:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/67197221/163701689-9b51317a-3a52-450f-8138-860da6ef2214.png">

I think my query is right but the response code is 400. Could you tell me what's wrong with my query please?

Best,
Zili
