### ISSUE TITLE
Issue on string-based query 

### ISSUE THREAD

**Issue by ZiliGit** [cambialens/lens-api-doc#51]
Hi,

Sorry I encountered another question when I try to use the string-based query to get the filtered patents:
<img width="822" alt="image" src="https://user-images.githubusercontent.com/67197221/163701689-9b51317a-3a52-450f-8138-860da6ef2214.png">

I think my query is right but the response code is 400. Could you tell me what's wrong with my query please?

Best,
Zili

_Originally posted by @ZiliGit in https://github.com/cambialens/lens-api-doc/issues/50#issuecomment-1100807227_

**Comment by rosharma9** [comment]
Can you please post the query text instead of screenshot? Also, would be great if you could use enclose the code blocks into triple backticks ` ``` ` like [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
