### ISSUE TITLE
swagger.yaml bugs

### ISSUE THREAD

**Issue by tomale69** [cambialens/lens-api-doc#53]
Hello Support,
I am developing an interface to Lens Scholarly (we have recently purchased a licence for this) and I have used the swagger.yaml file to automate the creation of java classes needed to wrap your api. However, I noticed there are some bugs in the file (see attached file). Would it be possible to fix these those errors? 
Thank you very much and have a nice day. 
Best Regards. 
Alessandro Tomasini
Saes Getters S.p.A.
[Swagger.yaml.Errors.txt](https://github.com/cambialens/lens-api-doc/files/8603178/Swagger.yaml.Errors.txt)

**Comment by rosharma9** [comment]
Hi Alessandro,
Here is a fixed [schema](https://github.com/cambialens/lens-api-doc/files/8606642/swagger.yaml.txt), we will publish it soon. 
Also, I recommend to find the response schema from following endpoint as we are constantly evolving and this endpoint is always consistent with what you receive in response.
`GET https://api-dev.api.lens.org/schema/scholarly?token=YOUR_TOKEN`
Let us know if you have more issues.
Cheers,
Roshan

**Comment by tomale69** [comment]
Hi Roshan,
First of all, thank you for your quick reply.
The new swagger.yaml seems to be correct except for the "post" reply patterns that are still missing. See below for details.
I tried using https://api-dev.api.lens.org instead of https://api.lens.org (I used the same pkey I created earlier) but it returns an unauthorized access error.
Thank you.
Regards
Alessandro

Line 47
Actually
        '200':
          description: Valid response from the server
Should be
        '200':
          description: Valid response from the server
          schema:
            $ref: '#/definitions/ScholarApiResponse'

Line 134
Actually
        '200':
          description: Valid response from the server
Should be
        '200':
          description: Valid response from the server
          schema:
            $ref: '#/definitions/PatentApiResponse'

Line 226
Actually
        '200':
          description: Valid response from the server
Should be
        '200':
          description: Valid response from the server
          schema:
            $ref: '#/definitions/ScholarApiResponse'

**Comment by rosharma9** [comment]
Thank you Alessandro,
I have fixed the url for the schema. 
GET `https://api.lens.org/schema/scholarly?token=YOUR_TOKEN`
I will attach the schema in the responses like you've suggested.
Thanks,
Roshan

**Comment by poldham** [comment]
I think this is related to the above. I think there may be a bug with the swagger page authentication. When I enter my key in authorise (I know it is valid because I can run queries to the API without an issue) the POST sections for scholar and patents remain locked. I have tried several times with no success. As our queries are constructed using POST this is proving to be a bit frustrating. If this could be investigated that would be much appreciated.

**Comment by rosharma9** [comment]
If you click on the lock icon at the right of the POST method (after entering the access key and get authorised), you will see the status as authorised as in the screenshot attached. You can then click on `Try it out` and `execute` the query successfully.
<img width="1414" alt="Screen Shot 2022-07-10 at 7 33 37 pm" src="https://user-images.githubusercontent.com/47509149/178139326-1277a703-99fb-4bbe-86ff-9b72e95c7a0d.png">

**Comment by poldham** [comment]
Thanks, I have no idea what was going on as that is precisely what I was doing yesterday (hence the issue). However, it is indeed working. Many thanks for the rapid support.
