### ISSUE TITLE
Question on Transition from MAG to OpenAlex.

### ISSUE THREAD

**Issue by poldham** [cambialens/lens-api-doc#54]
Hi, Could you advise if there is a roadmap for the transition from MAG to Open Alex for the Lens api? As I understand it the MAG version of Open Alex is discontinued from the 6th of July. An indication of planned changes to the API ... such as to available fields... would be very helpful as the changes could break existing code in packages that use the API. A table of some form in the change log page on Support would be one idea. That way, API users will have a chance to adjust their code. Many thanks.

**Comment by AaronBallagh** [comment]
G'day Paul,
Regarding the addition of OpenAlex data alongside MAG, there should be no changes to the Lens API as we integrate the OpenAlex data. We endeavor to keep the API data schema consistent and backwards compatible without introducing any breaking schema changes. And we notify API users of any changes through the Release Notes (https://about.lens.org/category/release-notes/), the Newsletter (http://eepurl.com/hrnBlT) and API documentation, which includes a change log (https://docs.api.lens.org/support.html#change-log).
Cheers, Aaron

**Comment by poldham** [comment]
Many Thanks Aaron, I guess that will teach me not to only read the API documentation pages! Good to know on Open Alex as I am seeing the ids feeding through. Thanks again, this issue can be closed. All the best, Paul
