### ISSUE TITLE
Grouped by simple family filter in API response

### ISSUE THREAD

**Issue by Siru645** [cambialens/lens-api-doc#55]
Hi,

I am trying to use Lens API query to get the simple family size under some patent subclass. I am wondering if there is some response fields that allow me to get the result of total simple famil size using API.

What I want to achieve is something looks like the following highlight result:
![image](https://user-images.githubusercontent.com/57119041/180336228-f8ffd89f-c7e7-444c-8491-021ac6859079.png)

Best,
Siru

**Comment by AaronBallagh** [comment]
Hi Siru645, 
There is no response field available for simple families in the API currently. We will be adding a param or endpoint for families in future, but for now you would need to request the family information for each record to determine the number of simple families represented in the response.

**Comment by poldham** [comment]
Hi @AaronBallagh,

@Siru645 seems to have read my mind on this. It would be very helpful if there was some way to group results by simple or extended families with the API as a query option to reproduce the public user interface. That would aid with reproducibility of methods (when writing papers) but more importantly reduce the volume of date passed through the API and the need to deduplicate the records down to first family members for analysis purposes (which means a lot gets discarded anyway). So, I think this would have a number of advantages. In the meantime, as you point out, retrieving the family member data in a second set of calls is the solution.

**Comment by Siru645** [comment]
I got the point, thanks for the reply.
________________________________
