### ISSUE TITLE
Swagger UI not loading

### ISSUE THREAD

**Issue by zilch42** [cambialens/lens-api-doc#6]
Hi, I'm getting the following error trying to load the swagger UI at the moment. 

> Unable to infer base url. This is common when using dynamic servlet registration or when the API is behind an API Gateway. The base url is the root of where all the swagger resources are served. For e.g. if the api is available at http://example.org/api/v2/api-docs then the base url is http://example.org/api/. Please enter the location manually:

**Comment by rosharma9** [comment]
Hi @zilch42 ! Can you please confirm if the URL is correct: [https://api.lens.org/swagger-ui.html](https://api.lens.org/swagger-ui.html). I am not able to replicate it.

**Comment by zilch42** [comment]
Its working again now ¯\_(ツ)_/¯
