### ISSUE TITLE
Documentation of Scholar API is missing publication_type values 

### ISSUE THREAD

**Issue by Beilstein** [cambialens/lens-api-doc#60]
The documentation of the Scholar API is missing some values for field publication_type. We need to create different implementation handlers based upon the publication_type, so we would like to find an exhaustive list of the range of possible values. So far in the returned data, we have found the following values that were NOT documented: "editorial", "letter", "preprint", "dissertation", "other".

**Comment by AaronBallagh** [comment]
Hello, thank you for this question.
We have just added the full list of publication types to the documentation, you can view the list here https://docs.api.lens.org/response-scholar.html#publication-types. I hope this helps, please let me know if you have any other questions.
Thank you,
Aaron
