### ISSUE TITLE
unable to scroll results on patents API

### ISSUE THREAD

**Issue by pessoag** [cambialens/lens-api-doc#66]
Using code based on [documentation](https://docs.api.lens.org/samples-scholar.html) for pagination, I receive an error because there is no 'scroll_id' on response. 

My query is working well but get only 20 results, even there is 51173 results available.

`request_body = '''{
  "query": "(inventor.residence:BR OR applicant.residence:BR OR owner_all.country: BR) AND (has_full_text:true OR has_description: true)"
  },
  "size": 1000,
  "scroll": "1m"
}'''
headers = {'Authorization': autorization, 'Content-Type': 'application/json'}`

**Comment by AaronBallagh** [comment]
It looks like your query is malformed, can you try this:
`request_body = '''{ "query": "(inventor.residence:BR OR applicant.residence:BR OR owner_all.country: BR) AND (has_full_text:true OR has_description: true)", "size": 1000, "scroll": "1m" }''' headers = {'Authorization': autorization, 'Content-Type': 'application/json'}`

**Comment by pessoag** [comment]
It works! Thank you very much! I know it was something quite simple
