### ISSUE TITLE
Sequence Metadata

### ISSUE THREAD

**Issue by poldham** [cambialens/lens-api-doc#68]
Hi, I am trying to construct a query using Swagger to obtain information such as sequence counts for records I know have a sequence. However, I am getting a 400 in the response. I'd appreciate any advice on this as all of the sequence related fields documented at [https://docs.api.lens.org/request-patent.html#sequence-count](https://docs.api.lens.org/request-patent.html#sequence-count) seem to return 400. 

I am probably missing something but the code below works on just the lens_id but 400s on the sequence.count. Many thanks for any help on this. 

{
    "query": {
        "terms": {
            "ids": ["000-021-670-665-910"]
        }
    },
    "size": 10,
    "include": ["lens_id", "sequence.count"]
}

**Comment by AaronBallagh** [comment]
G'day Paul,

I hope you are well! Thanks for this question. 

The `sequence.count` field is a request field only, we have not exposed the sequence metadata fields in the response yet. We will look at adding the sequence metadata fields (not the sequences themselves) to the response and I will let you know when they are available.

Cheers,

Aaron

**Comment by poldham** [comment]
Hi Aaron, 

Thanks for getting back so quickly and I hope you are doing well! Ah, I see. I think the importance of these fields is really for statistical use e.g. trends over time, by species, document section etc to inform policy debates for example under the Biodiversity Convention or the new High Seas Treaty etc. The sequences themselves are not of any interest for that use case.

All the best, 

Paul

**Comment by AaronBallagh** [comment]
Hi Paul,

I hope you are well! 

Just an update, we have added sequence listing metadata fields to the API response now, see https://docs.api.lens.org/response-patent.html#sequence-listing

Cheers,

Aaron
