### ISSUE TITLE
DOI request limit

### ISSUE THREAD

**Issue by zilch42** [cambialens/lens-api-doc#7]
Hi, 

Just wondering if there is a limit to the number of DOIs I can query at a time using the API? I'm not expecting to get all of the queried publications back as I'm using  has_patent_citations = true.

Sending all 704k of them returned a 500 error, but sending 5000 was ok, so guess it's somewhere in the middle. I'm hoping to minimise the total number of calls to the API so I don't hit my monthly limit. 

Cheers

**Comment by denizk** [comment]
Hi @zilch42 

Depending on how you're formulating your query, you might hit the default limit of 65,536 terms in a [terms query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html).

**Comment by zilch42** [comment]
Thanks @denizk. That's great.

It's easy to break my query up so its good to know what the limit is. 

Thanks.

**Comment by zilch42** [comment]
Just to give some feedback, I tried using a set size of 60,000 and got a error code 500. I reduced it to 30,000 and it was ok. I managed to successfully iterate through almost 900,000 DOIs using chunks that size. 

So there may be something else limiting the size of the request, before the 65,536 term limit is reached. 

Thanks

**Comment by denizk** [comment]
Thanks @zilch42 for the follow up. We had an additional payload limit in place which is now removed. Feel free to give it another go.
